"""ORM model for per-user MCP server configurations.

Each row stores one MCP server's full configuration (command, args, env,
url, headers, oauth, description) as JSON, scoped to a single user.

``is_system_default`` distinguishes servers seeded from the global
``extensions_config.json`` template (read-only, cannot be deleted) from
servers the user added themselves (fully editable / deletable).
"""

from __future__ import annotations

from datetime import UTC, datetime

from sqlalchemy import Boolean, DateTime, String, Text, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column

from kkoclaw.persistence.base import Base


class UserMcpServerRow(Base):
    __tablename__ = "user_mcp_servers"

    __table_args__ = (
        UniqueConstraint("user_id", "server_name", name="uq_user_mcp_user_server"),
    )

    id: Mapped[str] = mapped_column(String(64), primary_key=True)
    # UUID generated by the repository layer.

    user_id: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    # Foreign key to ``users.id`` is intentionally omitted — the persistence
    # layer keeps a soft reference so that deleting a user doesn't cascade
    # (orphaned rows are cleaned by an admin script). This mirrors the
    # ``feedback.user_id`` column pattern.

    server_name: Mapped[str] = mapped_column(String(128), nullable=False)
    # e.g. "web-search-prime", "Filesystem", "my-custom-server"

    config_json: Mapped[str] = mapped_column(Text, nullable=False)
    # Full :class:`~kkoclaw.config.extensions_config.McpServerConfig` serialised
    # as JSON — contains ``command``, ``args``, ``env``, ``url``, ``headers``,
    # ``oauth``, ``description``, ``type``, ``enabled``.

    enabled: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)

    is_system_default: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    # ``True`` for servers auto-seeded from ``extensions_config.json``.
    # These rows can be toggled (enabled/disabled) or have their config
    # overwritten by the user, but **cannot be deleted** via the API.

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(UTC),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(UTC),
        onupdate=lambda: datetime.now(UTC),
    )
