"""ORM model for per-user custom work modes.

Each row stores one custom work mode's configuration (mode_id, name,
description, orchestration_hint, focus_areas) scoped to a single user.

Built-in modes (task / coding) are **not** stored here — they ship with
the system via :func:`kkoclaw.config.extensions_config._default_builtin_work_modes`
and are merged with the user's custom rows at resolve time.

``is_system_default`` is intentionally omitted: every row in this table
is user-owned and fully editable / deletable. Built-in modes cannot be
deleted because they don't have a row here.
"""

from __future__ import annotations

from datetime import UTC, datetime

from sqlalchemy import Boolean, DateTime, String, Text, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column

from kkoclaw.persistence.base import Base


class UserWorkModeRow(Base):
    __tablename__ = "user_work_modes"

    __table_args__ = (
        UniqueConstraint("user_id", "mode_id", name="uq_user_work_mode_user_mode"),
    )

    id: Mapped[str] = mapped_column(String(64), primary_key=True)
    # UUID generated by the repository layer.

    user_id: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    # Foreign key to ``users.id`` is intentionally omitted — the persistence
    # layer keeps a soft reference so that deleting a user doesn't cascade
    # (orphaned rows are cleaned by an admin script). This mirrors the
    # ``feedback.user_id`` and ``user_mcp_servers.user_id`` column patterns.

    mode_id: Mapped[str] = mapped_column(String(64), nullable=False)
    # Slug-style identifier (e.g. "research", "finance", "writing").
    # Must not collide with builtin ids ("task", "coding") — enforced by
    # the repository / router layer.

    name: Mapped[str] = mapped_column(String(128), nullable=False)
    # Human-readable display name (e.g. "研究模式").

    description: Mapped[str] = mapped_column(Text, nullable=False, default="")
    # One-line summary for humans (≤50 chars recommended).

    orchestration_hint: Mapped[str] = mapped_column(Text, nullable=False, default="")
    # Mode-specific task orchestration guidance injected into the lead
    # agent's system prompt (≤2000 chars recommended). This is the core
    # "prompt design" field that shapes the agent's behavior in this mode.

    focus_areas_json: Mapped[str] = mapped_column(Text, nullable=False, default="[]")
    # JSON-encoded list of focus area tags (e.g. ["research", "papers"]).

    icon: Mapped[str] = mapped_column(String(64), nullable=False, default="Bot")
    # Lucide icon name (e.g. "Bot", "Briefcase") or emoji used by the
    # frontend sidebar to render this mode's entry. Defaults to "Bot".
    # Built-in modes do not read this column — their icons are resolved
    # from a hard-coded map in the router.

    enabled: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)
    # Soft-disable toggle (reserved for future use; disabled modes are
    # hidden from the selector).

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(UTC),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(UTC),
        onupdate=lambda: datetime.now(UTC),
    )
